# Generated by Django 5.1.4 on 2024-12-19 11:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('a_image', models.ImageField(upload_to='a_images')),
            ],
        ),
        migrations.CreateModel(
            name='AttractionsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction_event', models.CharField(max_length=155)),
                ('attraction_event_image', models.ImageField(upload_to='attraction_event_images')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert_name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture_name', models.CharField(max_length=35)),
                ('culture_description', models.TextField()),
                ('culture_image', models.ImageField(upload_to='culture-images')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_name', models.CharField(max_length=55)),
                ('gallery_image', models.ImageField(upload_to='gellery_images')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_name', models.CharField(max_length=55)),
                ('home_image', models.ImageField(blank=True, null=True, upload_to='home_images')),
                ('home_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HotelsRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotels_region_name', models.CharField(max_length=155)),
                ('hotels_region_image', models.ImageField(upload_to='hotels_region_images')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen_name', models.CharField(max_length=155)),
                ('kitchen_image', models.ImageField(upload_to='kitchen_images')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Leisure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leisure_name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PopularRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular_name', models.CharField(max_length=155)),
                ('popular_image', models.ImageField(upload_to='popular_images')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=55)),
                ('region_image', models.ImageField(upload_to='region_images')),
                ('region_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater_name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tourism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourism_name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KG')),
                ('user_picture', models.ImageField(blank=True, null=True, upload_to='user_pictures')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AttractionsEventReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('attractions_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions_event', to='country.attractionsevent')),
                ('attractions_events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.attractionsevent')),
                ('client_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=300)),
                ('currency_description', models.TextField()),
                ('hand_image', models.ImageField(upload_to='currency_images')),
                ('culture_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culture_currency', to='country.culture')),
            ],
        ),
        migrations.CreateModel(
            name='EventCinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_cinema', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('text_cinema', models.CharField(max_length=155)),
                ('cinema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='EventConcert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_concert', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('text_concert', models.CharField(max_length=155)),
                ('concert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.concert')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('client_gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_reviews', to=settings.AUTH_USER_MODEL)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_name', models.CharField(max_length=300)),
                ('games_description', models.TextField()),
                ('games_image', models.ImageField(upload_to='games_images')),
                ('culture_games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culture_games', to='country.culture')),
            ],
        ),
        migrations.CreateModel(
            name='HandCrafts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_name', models.CharField(max_length=300)),
                ('hand_description', models.TextField()),
                ('hand_image', models.ImageField(upload_to='hand_images')),
                ('culture_hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culture_hand', to='country.culture')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_favorite', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='country.home')),
            ],
        ),
        migrations.CreateModel(
            name='AttractionsHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction_name', models.CharField(max_length=155)),
                ('attraction_image', models.ImageField(blank=True, null=True, upload_to='attraction_images')),
                ('description', models.TextField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions_home', to='country.home')),
            ],
        ),
        migrations.CreateModel(
            name='HomeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Рейтинг')),
                ('attractions_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions_review', to='country.attractionshome')),
                ('client_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_reviews', to=settings.AUTH_USER_MODEL)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.home')),
            ],
        ),
        migrations.CreateModel(
            name='HotelsReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('client_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels_region_reviews', to=settings.AUTH_USER_MODEL)),
                ('hotel_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.hotelsregion')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('client_kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_reviews', to=settings.AUTH_USER_MODEL)),
                ('kitchen_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.kitchen')),
            ],
        ),
        migrations.CreateModel(
            name='EventLeisure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_leisure', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('text_leisure', models.CharField(max_length=155)),
                ('leisure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.leisure')),
            ],
        ),
        migrations.CreateModel(
            name='EventMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_master', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('text_master', models.CharField(max_length=155)),
                ('master_classes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.masterclasses')),
            ],
        ),
        migrations.CreateModel(
            name='NationalClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes_name', models.CharField(max_length=300)),
                ('clothes_description', models.TextField()),
                ('clothes_image', models.ImageField(upload_to='clothes_images')),
                ('culture_clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culture_clothes', to='country.culture')),
            ],
        ),
        migrations.CreateModel(
            name='NationalInstruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_name', models.CharField(max_length=300)),
                ('national_description', models.TextField()),
                ('national_image', models.ImageField(upload_to='national_images')),
                ('culture_national', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culture_national', to='country.culture')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attractions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.attractionshome')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='country.favorite')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.gallery')),
                ('popular_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.popularregion')),
            ],
        ),
        migrations.CreateModel(
            name='PopularReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Рейтинг')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('popular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_reviews', to='country.popularregion')),
            ],
        ),
        migrations.AddField(
            model_name='popularregion',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_region', to='country.region'),
        ),
        migrations.CreateModel(
            name='PlacesRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('stars', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.placesregion')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='country.region')),
            ],
        ),
        migrations.AddField(
            model_name='kitchen',
            name='kitchen_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels_region_image', to='country.region'),
        ),
        migrations.AddField(
            model_name='hotelsregion',
            name='hotels_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels_region', to='country.region'),
        ),
        migrations.CreateModel(
            name='EventTheater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_theater', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('text_theater', models.CharField(max_length=155)),
                ('theater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.theater')),
            ],
        ),
        migrations.CreateModel(
            name='ToTry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='What_to_try', to='country.region')),
            ],
        ),
        migrations.CreateModel(
            name='ToTryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='to_try_image/')),
                ('to_try', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='country.totry')),
            ],
        ),
        migrations.CreateModel(
            name='EventTourism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourism_master', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('text_tourism', models.CharField(max_length=155)),
                ('tourism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.tourism')),
            ],
        ),
    ]
