# Generated by Django 5.1.4 on 2024-12-15 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture_name', models.CharField(max_length=35)),
                ('culture_description', models.TextField()),
                ('culture_image', models.ImageField(upload_to='culture-images')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=300)),
                ('currency_description', models.TextField()),
                ('hand_image', models.ImageField(upload_to='currency_images')),
                ('culture_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culture_currency', to='country.culture')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_name', models.CharField(max_length=300)),
                ('games_description', models.TextField()),
                ('games_image', models.ImageField(upload_to='games_images')),
                ('culture_games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culture_games', to='country.culture')),
            ],
        ),
        migrations.CreateModel(
            name='HandCrafts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_name', models.CharField(max_length=300)),
                ('hand_description', models.TextField()),
                ('hand_image', models.ImageField(upload_to='hand_images')),
                ('culture_hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culture_hand', to='country.culture')),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen_name', models.CharField(max_length=300)),
                ('kitchen_description', models.TextField()),
                ('kitchen_image', models.ImageField(upload_to='kitchen_images')),
                ('culture_kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culture_kitchen', to='country.culture')),
            ],
        ),
        migrations.CreateModel(
            name='NationalClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes_name', models.CharField(max_length=300)),
                ('clothes_description', models.TextField()),
                ('clothes_image', models.ImageField(upload_to='clothes_images')),
                ('culture_clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culture_clothes', to='country.culture')),
            ],
        ),
        migrations.CreateModel(
            name='NationalInstruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_name', models.CharField(max_length=300)),
                ('national_description', models.TextField()),
                ('national_image', models.ImageField(upload_to='national_images')),
                ('culture_national', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culture_national', to='country.culture')),
            ],
        ),
    ]
