# Generated by Django 5.1.4 on 2024-12-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturekitchen',
            name='kitchen_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='culturekitchen',
            name='kitchen_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='culturekitchen',
            name='kitchen_name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='culturekitchen',
            name='kitchen_name_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_name_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='games_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='games_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='games_name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='games_name_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='handcrafts',
            name='hand_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='handcrafts',
            name='hand_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='handcrafts',
            name='hand_name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='handcrafts',
            name='hand_name_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nationalclothes',
            name='clothes_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nationalclothes',
            name='clothes_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nationalclothes',
            name='clothes_name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nationalclothes',
            name='clothes_name_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nationalinstruments',
            name='national_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nationalinstruments',
            name='national_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nationalinstruments',
            name='national_name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nationalinstruments',
            name='national_name_ru',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
