# Generated by Django 5.1.4 on 2024-12-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='from_user',
            field=models.CharField(default=1, max_length=62),
            preserve_default=False,
        ),
    ]
