# Generated by Django 5.1.4 on 2024-12-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_attractions_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='mian_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_image/'),
        ),
    ]
