# Generated by Django 5.1.4 on 2024-12-24 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_culturekitchen_kitchen_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='attraction_name_ar',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='attractions',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='culture_description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='culture_name_ar',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='culturekitchen',
            name='kitchen_description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='culturekitchen',
            name='kitchen_name_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_name_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='gallery_name_ar',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='games_description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='games_name_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='handcrafts',
            name='hand_description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='handcrafts',
            name='hand_name_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='home_description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='home_name_ar',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='address_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='cars_bikes_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='name_ar',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='kitchen_name_ar',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='nationalclothes',
            name='clothes_description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nationalclothes',
            name='clothes_name_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nationalinstruments',
            name='national_description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nationalinstruments',
            name='national_name_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='placesregion',
            name='text_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placesregion',
            name='user_name_ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='popularplaces',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='popularplaces',
            name='popular_name_ar',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region_description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_ar',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='totry',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='totry',
            name='first_description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='totry',
            name='second_description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='totry',
            name='to_name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
