# Generated by Django 5.1.4 on 2024-12-16 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_placesregion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteregion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_region', to='country.region'),
        ),
        migrations.CreateModel(
            name='FavoriteHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_favorite', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='country.region')),
            ],
        ),
        migrations.CreateModel(
            name='HotelsRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotels_region_name', models.CharField(max_length=155)),
                ('hotels_region_image', models.ImageField(upload_to='hotels_region_images')),
                ('description', models.TextField()),
                ('hotels_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels_region_image', to='country.region')),
            ],
        ),
        migrations.CreateModel(
            name='HotelsReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('client_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels_region_reviews', to=settings.AUTH_USER_MODEL)),
                ('hotel_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.hotelsregion')),
            ],
        ),
    ]
