# Generated by Django 5.1.4 on 2024-12-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_attractions_mian_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attractions',
            old_name='mian_image',
            new_name='main_image',
        ),
        migrations.RenameField(
            model_name='hotels',
            old_name='mian_image',
            new_name='main_image',
        ),
        migrations.RenameField(
            model_name='kitchen',
            old_name='mian_image',
            new_name='main_image',
        ),
    ]
