# Generated by Django 5.1.4 on 2024-12-25 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_attractions_attraction_name_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region_Categoty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_category', models.CharField(choices=[('Chui', 'Chui'), ('Talas', 'Talas'), ('Batken', 'Batken'), ('Osh', 'Osh'), ('Naryn', 'Naryn'), ('Issyk-Kul', 'Issyk-Kul'), ('Jalal-Abad', 'Jalal-Abad')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='region_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='country.region_categoty'),
            preserve_default=False,
        ),
    ]
