# Generated by Django 5.1.4 on 2024-12-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_region_categoty_region_region_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='cars_bikes',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='cars_bikes_ar',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='cars_bikes_en',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='cars_bikes_ru',
        ),
        migrations.AddField(
            model_name='hotels',
            name='bikes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hotels',
            name='bikes_ar',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='bikes_en',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='bikes_ru',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='cars',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hotels',
            name='cars_ar',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='cars_en',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='cars_ru',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
