# Generated by Django 5.1.4 on 2024-12-19 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_rename_homereview_attractionreview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularplaces',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_places', to='country.region'),
        ),
    ]
