# Generated by Django 5.1.4 on 2024-12-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_alter_popularplaces_region'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotelsRegion',
            new_name='Hotels',
        ),
    ]
