# Generated by Django 5.1.4 on 2024-12-16 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_rename_kitchen_description_kitchen_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction_event', models.CharField(max_length=155)),
                ('attraction_event_image', models.ImageField(upload_to='attraction_event_images')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert_name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leisure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leisure_name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater_name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tourism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourism_name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='favoritehotel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favoritekitchen',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favoriteregion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favoriteuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='client',
        ),
        migrations.CreateModel(
            name='AttractionsEventReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('attractions_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions_event', to='country.attractionsevent')),
                ('attractions_events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.attractionsevent')),
                ('client_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventCinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_cinema', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('text_cinema', models.CharField(max_length=155)),
                ('cinema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='EventConcert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_concert', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('text_concert', models.CharField(max_length=155)),
                ('concert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.concert')),
            ],
        ),
        migrations.RenameModel(
            old_name='FavoriteHome',
            new_name='Favorite',
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attractions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.attractionshome')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='country.favorite')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.gallery')),
                ('popular_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.popularregion')),
            ],
        ),
        migrations.CreateModel(
            name='EventLeisure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_leisure', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('text_leisure', models.CharField(max_length=155)),
                ('leisure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.leisure')),
            ],
        ),
        migrations.CreateModel(
            name='EventMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_master', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('text_master', models.CharField(max_length=155)),
                ('master_classes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.masterclasses')),
            ],
        ),
        migrations.CreateModel(
            name='EventTheater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_theater', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('text_theater', models.CharField(max_length=155)),
                ('theater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.theater')),
            ],
        ),
        migrations.CreateModel(
            name='EventTourism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourism_master', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('text_tourism', models.CharField(max_length=155)),
                ('tourism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.tourism')),
            ],
        ),
        migrations.DeleteModel(
            name='FavoriteGallery',
        ),
        migrations.DeleteModel(
            name='FavoriteHotel',
        ),
        migrations.DeleteModel(
            name='FavoriteKitchen',
        ),
        migrations.DeleteModel(
            name='FavoriteRegion',
        ),
        migrations.DeleteModel(
            name='FavoriteUser',
        ),
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
