# Generated by Django 5.1.4 on 2024-12-25 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_remove_hotels_cars_bikes_remove_hotels_cars_bikes_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='popular_places',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='country.popularplaces'),
            preserve_default=False,
        ),
    ]
