# Generated by Django 5.1.4 on 2024-12-19 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_attractionsevent_cinema_concert_leisure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='home_description',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='region_description',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='attractionculture',
            name='a_name',
        ),
        migrations.RemoveField(
            model_name='attractionshome',
            name='attraction_name',
        ),
        migrations.RemoveField(
            model_name='home',
            name='home_name',
        ),
        migrations.RemoveField(
            model_name='homereview',
            name='client_home',
        ),
        migrations.RemoveField(
            model_name='popularregion',
            name='popular_name',
        ),
        migrations.RemoveField(
            model_name='region',
            name='region_name',
        ),
        migrations.AddField(
            model_name='attractionculture',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attractionculture',
            name='name',
            field=models.CharField(default=1, max_length=52),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attractionshome',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attractionshome',
            name='name',
            field=models.CharField(default=1, max_length=52),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='name',
            field=models.CharField(default=1, max_length=52),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homereview',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homereview',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homereview',
            name='name',
            field=models.CharField(default=1, max_length=52),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popularregion',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popularregion',
            name='name',
            field=models.CharField(default=1, max_length=52),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popularreview',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popularreview',
            name='name',
            field=models.CharField(default=1, max_length=52),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='name',
            field=models.CharField(default=1, max_length=52),
            preserve_default=False,
        ),
    ]
