# Generated by Django 5.1.4 on 2024-12-19 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_rename_hotelsregion_hotels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='hotels_region_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='hotels',
            old_name='hotels_region_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hotels',
            old_name='hotels_region',
            new_name='region',
        ),
        migrations.RemoveField(
            model_name='hotelsreview',
            name='hotel_region',
        ),
        migrations.AddField(
            model_name='hotelsreview',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reviews', to='country.hotels'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotelsreview',
            name='client_hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_hotel', to=settings.AUTH_USER_MODEL),
        ),
    ]
