# Generated by Django 5.1.4 on 2024-12-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0008_hotelsreview_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotels',
            name='amenities',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotels',
            name='bathroom',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hotels',
            name='bedroom',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hotels',
            name='cars_bikes',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotels',
            name='pets',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotels',
            name='price_long_period',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotels',
            name='price_medium_period',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotels',
            name='price_short_period',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotels',
            name='safety_hygiene',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
