# Generated by Django 5.1.4 on 2024-12-20 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0009_hotels_address_hotels_amenities_hotels_bathroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='image',
        ),
        migrations.CreateModel(
            name='HotelsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel_images/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_image', to='country.hotels')),
            ],
        ),
    ]
