# Generated by Django 5.1.4 on 2024-12-20 12:44

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0010_remove_hotels_image_hotelsimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='kitchen_image',
        ),
        migrations.AddField(
            model_name='kitchen',
            name='meal',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Brunch', 'Brunch'), ('Open Late', 'Open Late'), ('Drinks', 'Drinks')], default=1, max_length=46),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitchen',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitchen',
            name='specialized_menu',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='KitchenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='kitchen_images/')),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_image', to='country.kitchen')),
            ],
        ),
    ]
