# Generated by Django 5.1.4 on 2024-12-20 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0012_kitchen_type_of_cafe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchenreview',
            name='client_kitchen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kitchenreview',
            name='kitchen_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_reviews', to='country.kitchen'),
        ),
    ]
