# Generated by Django 5.1.4 on 2025-01-22 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0012_remove_hotels_bikes_ar_remove_hotels_bikes_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='popular_places',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='popular_places', to='country.popularplaces'),
        ),
    ]
