# Generated by Django 5.1.4 on 2024-12-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0013_alter_kitchenreview_client_kitchen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenreview',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
