# Generated by Django 5.1.4 on 2025-01-22 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0013_attractions_popular_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attractions',
            name='region',
        ),
        migrations.AddField(
            model_name='attractions',
            name='region_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.region_categoty'),
        ),
    ]
