# Generated by Django 5.1.4 on 2025-01-22 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0014_remove_attractions_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='popular_places',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.popularplaces'),
        ),
    ]
