# Generated by Django 5.1.4 on 2024-12-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0014_kitchenreview_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitchen',
            old_name='meal',
            new_name='meal_time',
        ),
    ]
