# Generated by Django 5.1.4 on 2024-12-20 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0015_rename_meal_kitchen_meal_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='attractionseventreview',
            name='attractions_event',
        ),
        migrations.RemoveField(
            model_name='attractionseventreview',
            name='attractions_events',
        ),
        migrations.RemoveField(
            model_name='attractionseventreview',
            name='client_event',
        ),
        migrations.RemoveField(
            model_name='eventcinema',
            name='cinema',
        ),
        migrations.RemoveField(
            model_name='eventconcert',
            name='concert',
        ),
        migrations.RemoveField(
            model_name='eventleisure',
            name='leisure',
        ),
        migrations.RemoveField(
            model_name='eventmaster',
            name='master_classes',
        ),
        migrations.RemoveField(
            model_name='eventtheater',
            name='theater',
        ),
        migrations.RemoveField(
            model_name='eventtourism',
            name='tourism',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=52)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('address', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_category', to='country.eventcategories')),
            ],
        ),
        migrations.DeleteModel(
            name='AttractionsEvent',
        ),
        migrations.DeleteModel(
            name='AttractionsEventReview',
        ),
        migrations.DeleteModel(
            name='Cinema',
        ),
        migrations.DeleteModel(
            name='EventCinema',
        ),
        migrations.DeleteModel(
            name='Concert',
        ),
        migrations.DeleteModel(
            name='EventConcert',
        ),
        migrations.DeleteModel(
            name='EventLeisure',
        ),
        migrations.DeleteModel(
            name='Leisure',
        ),
        migrations.DeleteModel(
            name='EventMaster',
        ),
        migrations.DeleteModel(
            name='MasterClasses',
        ),
        migrations.DeleteModel(
            name='EventTheater',
        ),
        migrations.DeleteModel(
            name='Theater',
        ),
        migrations.DeleteModel(
            name='EventTourism',
        ),
        migrations.DeleteModel(
            name='Tourism',
        ),
    ]
