# Generated by Django 5.1.4 on 2025-01-22 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0015_kitchen_popular_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='kitchen_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels_region_image', to='country.region_categoty'),
        ),
    ]
