# Generated by Django 5.1.4 on 2025-01-22 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0016_alter_kitchen_kitchen_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='kitchen_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.region_categoty'),
        ),
    ]
