# Generated by Django 5.1.4 on 2024-12-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0017_event_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttractionsHome',
            new_name='Attractions',
        ),
        migrations.DeleteModel(
            name='AttractionCulture',
        ),
        migrations.RenameField(
            model_name='attractionreview',
            old_name='attractions_home',
            new_name='attractions',
        ),
    ]
