# Generated by Django 5.1.4 on 2025-01-23 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0017_alter_kitchen_kitchen_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels_region', to='country.region_categoty'),
        ),
    ]
