# Generated by Django 5.1.4 on 2024-12-20 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0018_rename_attractionshome_attractions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attractions',
            name='attraction_image',
        ),
        migrations.CreateModel(
            name='AttractionsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='attartions_image/')),
                ('attractions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='country.attractions')),
            ],
        ),
    ]
