# Generated by Django 5.1.4 on 2025-01-23 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0019_remove_currency_currency_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency_description',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_description', to='country.currency'),
        ),
        migrations.AlterField(
            model_name='currency_image',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_image', to='country.currency'),
        ),
    ]
