# Generated by Django 5.1.4 on 2024-12-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0019_remove_attractions_attraction_image_attractionsimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attractionreview',
            name='home',
        ),
        migrations.RemoveField(
            model_name='attractions',
            name='home',
        ),
    ]
