# Generated by Django 5.1.4 on 2024-12-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0020_remove_attractionreview_home_remove_attractions_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenreview',
            name='atmosphere_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='kitchenreview',
            name='nutrition_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='kitchenreview',
            name='price_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='kitchenreview',
            name='service_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
