# Generated by Django 5.1.4 on 2025-01-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0013_merge_20250120_1345'),
        ('country', '0020_alter_currency_description_currency_and_more'),
    ]

    operations = [
    ]
