# Generated by Django 5.1.4 on 2024-12-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0021_kitchenreview_atmosphere_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultureKitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen_name', models.CharField(max_length=300)),
                ('kitchen_description', models.TextField()),
                ('kitchen_image', models.ImageField(upload_to='kitchen_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='currency',
            name='culture_currency',
        ),
        migrations.RemoveField(
            model_name='games',
            name='culture_games',
        ),
        migrations.RemoveField(
            model_name='handcrafts',
            name='culture_hand',
        ),
        migrations.RemoveField(
            model_name='nationalclothes',
            name='culture_clothes',
        ),
        migrations.RemoveField(
            model_name='nationalinstruments',
            name='culture_national',
        ),
    ]
