# Generated by Django 5.1.4 on 2024-12-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0024_alter_galleryreview_client_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='totry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='to_try_image/'),
        ),
        migrations.DeleteModel(
            name='ToTryImage',
        ),
    ]
